redis:
  image: redis

rickbot:
  image: rickbot-bot
  links:
    - redis
  enviroment:
    - REDIS_URL=redis://redis/
    - RICKBOT_TOKEN=...

rickbot-web:
  image: rickbot-web
  links:
    - redis
  enviroment:
    - REDIS_URL=redis://redis/
    - OAUTH2_CLIENT_ID=...
    - OAUTH2_CLIENT_SECRET=...
    - OAUTH2_REDIRECT_URI=...
    - SECRET_KEY=...

  expose:
    - 5000

proxy:
  image: jwilder/nginx-proxy
